### ISSUE TITLE
way to many issues going on with this lib

### ISSUE THREAD

**Issue by kamijoutouma** [node-xmpp/node-xmpp#250]
you guys need to fix this lib its erroring everywhere its now so annoying that ive uninstalled this lib from my node modules

**Comment by sonnyp** [comment]
maybe the "weird git not found error" issue comes from https://github.com/node-xmpp/node-xmpp-component/commit/dba1f832e7e6170fa167f85e84074805b7ccd7a4#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R24 ? 

@kamijoutouma instead of installing node-xmpp could you try installing only the module you need, for example ```node-xmpp-client```.

**Comment by sonnyp** [comment]
No response, closing
