### ISSUE TITLE
How to scale node xmpp server

### ISSUE THREAD

**Issue by danilvalov** [node-xmpp/node-xmpp#315]
Hi.

I use node xmpp server in my project. And i need horizontal scaling my server because i have very high load on the server. How to do it?

Thanks.

**Comment by hyperlink** [comment]
We put our instances behind [HAProxy](http://www.haproxy.org/).

**Comment by danilvalov** [comment]
@hyperlink And how to synchronize all instances in realtime?
I want to have some instances on one domain and i need smart balancer for it.
If message come to first instance i need to receive it on other instances and re-send it to all users there.

**Comment by sonnyp** [comment]
@danilvalov can you give us more details about your setup?

TCP? BOSH? WebSocket? 
Why do you have such a high load? Do you mean high memory usage?

**Comment by hyperlink** [comment]
@danilvalov we use redis pubsub keyed on the jid to help coordinate this.

**Comment by danilvalov** [comment]
@sonnyp We are planing on 500k connections. But it's not important. I asked about horizontal scaling. It's general question.

@hyperlink Thank you! Do you use redis notifications for sync in real-time?
@sonnyp We are planing on 500k connections. But it's not important. I asked about horizontal scaling. It's general question.

@hyperlink Thank you! That's what I need!

**Comment by sonnyp** [comment]
@danilvalov it _is_ important.

If you plan on using BOSH you cannot use [Node.js cluster](https://nodejs.org/api/cluster.html) because you'll need sticky sessions.

Scaling horizontally is very fine but you gotta make sure you don't need 5000 nodes or it's a all new problem.

Here is my recommendations:

* Do not use BOSH, it is hard to scale and our implementation is clumsy
* Maybe use Node.js cluster to scale on your hosts CPUs
* As @hyperlink said, redis pubsub/store between your nodes works pretty well I've done that as well in the past.
* Avoid RabbitMQ / AMQP , from experience it doesn't make much sense with XMPP

The easy way is to "broadcast" every incoming c2s stanza to all nodes. It is simple and allows you to hook for any event on any node. Perfect to start with.

The harder way is to "broadcast" incoming c2s stanzas to nodes which have the recipient connected. Scales better but is a bit harder.

The best and hardest way is to have proper standalone clustering support in node-xmpp-server. Maybe one day? :smile:

**Comment by sonnyp** [comment]
Additionally [stream management](https://xmpp.org/extensions/xep-0198.html) helps mitigate the effects of a node crashing

**Comment by danilvalov** [comment]
@sonnyp 
> The easy way is to "broadcast" every incoming c2s stanza to all nodes. It is simple and allows you to hook for any event on any node. Perfect to start with.

If we have 50 000 servers then we need to send 50 000 requests and handle it 50 000 times on all servers. If we send 50 messages in second on every server then we need to handle (50 x 50 000) 2,5 millions requests on every server because we get all 2.5 millions requests from all servers on every server. It's very hard for any server.

Do you have ideas how to send requests to needed servers only (for example, with needed rooms).

P.S. Sorry. You're right, it's really important. We use basic [node-xmpp-server](https://github.com/node-xmpp/node-xmpp/tree/master/packages/node-xmpp-server) with tls and extending and customization xmpp-protocol (we use custom attributes for messages and specific stanzas for other events).

**Comment by sonnyp** [comment]
> If we have 50 000 servers then we need to send 50 000 requests and handle it 50 000 times on all servers. If we send 50 messages in second on every server then we need to handle (50 x 50 000) 2,5 millions requests on every server because we get all 2.5 millions requests from all servers on every server. It's very hard for any server.

Realistically you won't need/have 50k nodes. But indeed, that's why I said it is the simple solution to start with (in the case you don't already have that much connections). If you're starting a project, you don't want to deal with too much cluster complexity so IMHO it's still the right way to start with (we didn't covered them but they are others complex things to handle such as node crash recovery)

> Do you have ideas how to send requests to needed servers only (for example, with needed rooms).

With redis, do as @hyperlink said, use JID based redis pusub.

**Comment by sonnyp** [comment]
About crash recovery, if you use presence you have to make sure you'll send a presence unavailable on behalf of all presences connected to their subscribers. So you need a way for all nodes to know when a node dies/crash.

**Comment by danilvalov** [comment]
Now i want to use [redis pub/sub library for node](https://github.com/louischatriot/node-redis-pubsub) with subscribing on active rooms (by room id, i use in my project communication between users in rooms only, without user to user communication) on every instance (thanks @hyperlink for idea). And it help me optimizing scaling of instances.

Thanks @sonnyp @hyperlink for the help.

**Comment by sonnyp** [comment]
@danilvalov I recommend using https://github.com/luin/ioredis

**Comment by danilvalov** [comment]
@hyperlink @sonnyp Please, help me with my scaling again.

I have one redis-server for synchronization between all instances. I keep active users in rooms to redis (for checking online/offline users in my app).

I have one problem: if one instance is crashed then i have irrelevant data in redis because this instance doesn't remove its users after that.

How to remove users from redis after instance crashing? Or maybe you know the way how to check online/offline users in all rooms in all instanes.

**Comment by sonnyp** [comment]
@danilvalov that's one of the reason I recommended to route all stanzas to all nodes.

Basically each node stores in memory (or local redis but that's overkill) its own presence and the presences of other nodes.

This way you can query any node (and load balance) for the presence of a user and you don't have any SPOF.

**Comment by sonnyp** [comment]
@danilvalov check if redis allows somehow to subscribe to the list of subscribers. That way you'll get an event when a node crashes. From what I can remember it's not possible but double check and let us know.

**Comment by sonnyp** [comment]
@danilvalov what did you do at the end?

**Comment by danilvalov** [comment]
@sonnyp Sorry, i ended working with it only today.
I fixed it but i use bad method for it.

I created a daemon for check `client list` in Redis every minute. And i add special ids for redis client names and for all datas from instances. If my daemon finds id in redis data but doesn't find it in redis `client list` then daemon deletes this datas from redis.

It's very bad method but It works for me.
