### ISSUE TITLE
usage with react-native?

### ISSUE THREAD

**Issue by ramsestom** [node-xmpp/node-xmpp#324]
Hi

I am trying to use node-xmpp-client inside a react-native app but couldn't make it work yet.
react-native is supposed to be able to work with any lib working with browserify thanks to this module: https://github.com/originalgremlin/react-native-browser-builtins
but I am not even sure it is necessary though as react-native already support more node features than browserify (like tcp connections...)
Anyway, I tried to create a simple react-native app using node-xmpp-client (and using react-native-browser-builtins) but it fails complaining:` "Requiring unknown module "crypto".If you are sure the module is there, try restarting the packager or running "npm install".`
crypto is of course installed (react-native-crypto) and declared in my package.json file so I am not sure why it can't be found...
So as anyone already tried to use node-xmpp with react-native with success?
And to make node-xmpp work with browserify is there any specific procedure that need to be performed? (on previous reported issues I found mentions of a browserify branch of node-xmpp but wasn't able to find it in the github repository...)

**Comment by sonnyp** [comment]
Hey @ramsestom 

I've not yet worked with React native and node-xmpp but I'm definitely interesting in helping out, specially since we're working on better cross-platform support. https://github.com/node-xmpp/node-xmpp/pull/309/

Do you know what is printing the missing module complain?

Is there any mechanism to replace a node module with a react-native module? If so you could maybe use that to make node-xmpp use react-native-crypto rather than crypto ?

**Comment by ramsestom** [comment]
The error is thrown by the debbugger at runtime at this line:
`var Client = require('node-xmpp-client');`
If I comment it out, the app is running correctly

for the dependency override, I have 

```
 "dependencies": {
     ...
    "react-native-crypto": "^2.0.0",
    ...
}
"react-native": {
   ...
   "crypto": "react-native-crypto", 
  ...
}
 "browser": {
  ...
  "crypto": "react-native-crypto",
  ...
}
```
in my package.json file but doesn't seem to work...

Honestly I don't know if I would have the time to investigate much further; so I am already considering to switch to an other js XMPP library that might be easier to integrate into react-native (like xmpp-ftw that can use socket.io to handle connections and should be easier supported by react-native. I am used to strophe.js but couldn't make it work with react-native due to the "document" and "window" DOM elements dependency not correctly supported into react-native...)
Will keep you posted if I make node-xmpp to work with react-native

**Comment by sonnyp** [comment]
@ramsestom try https://github.com/otalk/stanza.io for the time being

**Comment by lloydwatkin** [comment]
@ramsestom xmpp-ftw only uses node-xmpp on the server, not the client so that is something you could do :)

**Comment by ggozad** [comment]
I would definitely be interested in reviving this :)
The crypto dependencies can be resolved now without resorting to disruptive hacks thanks to https://github.com/philikon/ReactNativify .
However `child_process` seems to be still a problem and I am not sure it should be a hard dependency for the client.

I would like to avoid stanza.io, I have an extensive library of protocols done for strophe which I would love to avoid rewriting. Is there interest in pursuing further the idea of node-xmpp-client for react native?

**Comment by ggozad** [comment]
`child_process` is only used in order to call `exec` and prebind. Commenting out the import makes `xmpp-node-client` run just fine on react native, I can connect and send a few stanzas without any problems.

My guess is that if one wanted to prebind he would do that outside of the library and pass `rid`, `sid` to bind. It makes no sense to exec a copy of the client from the client. As a bonus we would get instant react-native compatibility. /cc @lloydwatkin @sonnyp

**Comment by sonnyp** [comment]
Agree we can avoid `child_process`/`exec` although, do you actually need BOSH?

**Comment by ggozad** [comment]
I don't need personally need BOSH but it would be nice to keep it for others I guess. But I think the prebinding does not need to be part of the client, let me know if I am wrong:
A while ago I developed an app which used prebinding. It was a web app where XMPP was core but the user credentials were not exposed to the user. Instead the server would prebind a client and send the sid/rid to the user post authentication. Isn't this the case always when you want to prebind? As in there is an app logic outside the client that does that and somehow the rid/sid are passed to the client?

**Comment by lloydwatkin** [comment]
Could you just wrap the `required` in a try/catch?

```javascript
try { 
  require('blah') 
} catch (error) {
  console.log('BOSH not available')
}
```

**Comment by ggozad** [comment]
@lloydwatkin that might collide with how react preprocesses node modules but I can try it out and let you know. What I am arguing though is that:
1) Prebinding is not the client's responsibility. If the client has credentials then simple BOSH will do the job. Prebinding happens when the client has no credentials but the server has, then passes the rid/sid to the client.
2) It's not a great idea to spawn a process and output on the console the sid/rid

**Comment by sonnyp** [comment]
@ggozad I haven't played with BOSH for a while and I'm having a hard time remembering the specification but I think you might be right. `node-xmpp` is being rewritten and it something we should consider when we rewrite BOSH transport.
