### ISSUE TITLE
Add resource to component connections

### ISSUE THREAD

**Issue by Druotic** [node-xmpp/node-xmpp#332]
https://xmpp.org/extensions/xep-0225.html

Despite the extension being marked as 'deferred', it seems like a very useful extension to have implemented. It would allow for specifying an instance ID as the resource in the event that there are multiple instances of a component on the same domain. Currently, the domain is used for the 'to' field when initiating a component->server connection (see https://github.com/node-xmpp/node-xmpp/blob/master/packages/node-xmpp-component/lib/Component.js#L32)

Before/while I create the PR, I wanted to get some feedback to see if this is something that might stand a chance at getting merged. @sonnyp Thoughts?

**Comment by sonnyp** [comment]
@Druotic  why not using different component JIDs eg ```foo-1.bar```, ```foo-2.bar``` ... ? Also out of curiosity, what is your use case?

**Comment by Druotic** [comment]
@sonnyp After looking at [xep-0114](https://xmpp.org/extensions/xep-0114.html) again, I don't see where resources are specifically disallowed.  So, disregard my comments about xep-0225 and the deferred state. We can just refer to the non-deferred xep-0114. (xep-0225 is an extension to xep-0114) 

I'm interested in being able to distinguish instances for the same component while keeping the domain routable. For example, say I have two servers for the same component with IDs `foo-1`, `foo-2` with domain `component-name.bar.com`. I could prepend the IDs and have `foo-1.component-name.bar.com` and `foo-2.component-name.bar.com`, but these are no longer routable. It would be much cleaner if I could just specify `component-name.bar.com/foo-1`. The server identifier within a cluster seems very synonymous to a client resource in the traditional c2s jid definition, so it seems natural to identify a server by it's jid resource instead of a substring of the (non-routable) domain.

**Comment by sonnyp** [comment]
@Druotic it's not explicitly disallowed but it doesn't mean it's standard either. Specially since that's not how c2s connections negotiate resource. See https://xmpp.org/rfcs/rfc6120.html#bind

However I do agree it would be useful to have resource binding for components and other standard stream features which is the goal of XEP-0225.

Ideally we would be able to implement XEP-0225 as a plugin but in its current state node-xmpp doesn't allow to do that, I started working on that though https://github.com/node-xmpp/node-xmpp/pull/309/

I disagree on merging this PR as I don't think it's the right way to go as it would lead to interoperability issues. It's very unlikely your XMPP server will be able to handle that full component JID.

If you use node-xmpp-server I recommend you implement XEP-0225 in both node-xmpp-component and node-xmpp-server, I would accept such PR.

If you don't, you'll have to talk to your XMPP server team and see what can be done.

In both case I invite you to get involved and ping the XSF about the state of XEP-0225 and how we can move things forward.

**Comment by sonnyp** [comment]
Additionally if none of these solutions are viable for you, you may want to consider using XMPP clients rather than XMPP components.

**Comment by Druotic** [comment]
@sonnyp We use node-xmpp-server in a few different places.

> It's very unlikely your XMPP server will be able to handle that full component JID.
Why is this? We use the component server in node-xmpp-server to listen for jids of both forms and it has worked so far. That is, both `foo-1.component-name.bar.com` and `component-name.bar.com/foo-1`.

The real motivation for this change is that a component (from a completely different stack) sends us jids with the resource identifier and we would like to add test coverage for this case. Naturally, because our service is using node and we already use node-xmpp, we'd like to use the component package to do so. However, it doesn't fully support the same functionality without this PR.

**Comment by sonnyp** [comment]
@Druotic have you found a solution? what did you go with?

**Comment by Druotic** [comment]
@sonnyp A bit of a hack, but I ended up just overwriting the `streamTo` property of `Connection` between creating the component object and the connection being established. It's only used for test purposes to simulate a different xmpp component's behavior (not maintained by myself). I wouldn't use this approach for production code, but it works well enough for verification purposes.
